name: CI Tests

on:
  push:
    branches:
      - main
    paths:
      - "src.ts/**"

jobs:
  test-node:
    name: Run Node.js Tests
    runs-on: ubuntu-latest
    environment: poke-sdk-tests

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18.x ]
        test-type: [ esm ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build ESM and CommonJS (from TypeScript)
        run: npm run build-all

      - name: Run tests (${{ matrix.test-type }})
        run: npm run test-${{ matrix.test-type }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: "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"
